### ISSUE TITLE
robot tool macOS version

### ISSUE THREAD

**Issue by deryaT** [SNStatComp/RobotTool#1]
Dear all,
 We use last windows version of robot tool ,robot tool master. But also is there a version for macOS. We want to run the robot tool with macOS. How can we do this.

Thank you in advance...

**Comment by dwind** [comment]
You can install and run the RobotTool on MacOS in the same way as on Windows. See the README on how to install and run the RobotTool. You have to change your config.json file in map inst/app/config.
The name of the browser on MacOS is "Google Chrome".
